name: build
permissions: read-all

on: [ push, workflow_dispatch ]

jobs:
  plugin-linter:
    runs-on: ubuntu-latest
    container:
      image: buildkite/plugin-linter@sha256:ff299d6e870a756c88af77abd54b4294b5844fbce7c21edbae6611ebb2b2bf80
      volumes:
        - ${{ github.workspace }}:/plugin
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - name: Buildkite plugin linter
        run: lint --id opzkit/pre-commit

  plugin-tester:
    runs-on: ubuntu-latest
    container:
      image: buildkite/plugin-tester@sha256:64924c36eb3159e8c5463611d7ce69f4d490fa0198cc40d876e75357132973a4
      volumes:
        - ${{ github.workspace }}:/plugin
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - name: Buildkite plugin test
        run: "bats tests"
